<template functional>
  <div>
    <v-btn
      v-if="props.editBtn" 
      color="primary" 
      @click="props.editFn">
      Edit
    </v-btn>
    <v-btn
      v-if="props.completeBtn"
      color="success" 
      @click="props.completeFn">
      Complete
    </v-btn>
    <v-btn
      v-if="props.undoBtn" 
      color="success" 
      @click="props.undoFn">
      Undo
    </v-btn>
    <v-btn
      v-if="props.deleteBtn"
      @click="props.deleteFn" 
      color="error">
      Delete
    </v-btn>
    <v-btn
      v-if="props.saveBtn"
      color="success" 
      @click="props.saveFn">
      Save
    </v-btn>
    <v-btn
      v-if="props.cancelBtn" 
      @click="props.cancelFn" 
      color="error">
      Cancel
    </v-btn>

  </div>
</template>